export const EXPORT_CONFIG = {
  MOBILE_BATCH_SIZE: 10,
  DESKTOP_BATCH_SIZE: 30,
  MAX_FRAME_SKIP: 30,
  FALLBACK_FRAME_SKIP: 2,
  PROGRESS_UPDATE_INTERVAL_MS: 100,

  DEFAULT_BITRATE: 5_000_000,

  H264_CODECS: ['avc1.42001E', 'avc1.4D401E', 'avc1.64001E'] as const,
  WEBM_CODECS: ['vp09.00.10.08', 'vp9', 'vp8'] as const,

  DUPLICATE_FRAME_THRESHOLD: 0.95,

  MAX_ENCODER_RETRIES: 3,
  ENCODER_RETRY_DELAY_MS: 1000,
} as const;

export const REFRAMING_CONFIG = {
  BEZIER_SEGMENT_DURATION_SECONDS: 2,
  MOVING_AVERAGE_WINDOW: 5,
  MAX_HISTORY_SIZE_FRAMES: 60,
  MAX_VELOCITY_PX_PER_FRAME: 10,
  JITTER_THRESHOLD_PX: 3,

  DEFAULT_PADDING: 0.3,
  DEFAULT_SMOOTHNESS: 0.7,
} as const;

export const TRACKING_CONFIG = {
  BYTETRACK_SAMPLE_INTERVAL: 5,
  BOTSORT_SAMPLE_INTERVAL: 5,
  DEFAULT_CONFIDENCE_THRESHOLD: 0.3,
  NMS_IOU_THRESHOLD: 0.45,

  MIN_TRACK_LENGTH: 3,
  MAX_TRACK_AGE: 30,
} as const;
